#!/bin/bash
echo $ORACLE_HOME
$ORACLE_HOME/bin/sqlplus / as sysdba << EOF

startup

CREATE USER secretsysuser
  IDENTIFIED BY secretpassword
  DEFAULT TABLESPACE SYSTEM
  TEMPORARY TABLESPACE SYSTEM
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

-- 1 Role for secretsysuser 
GRANT DBA TO secretsysuser;
ALTER USER secretsysuser DEFAULT ROLE ALL;

-- 2 System Privileges for secretsysuser 
GRANT CREATE SESSION TO secretsysuser;
GRANT UNLIMITED TABLESPACE TO secretsysuser;

cREATE TABLESPACE app_data DATAFILE 
  '/opt/oracle/product/18c/dbhomeXE/dbs/daten1.dbf' SIZE 10M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
CREATE TEMPORARY TABLESPACE TEMP TEMPFILE
  '/opt/oracle/product/18c/dbhomeXE/dbs/temp.dbf' SIZE 10M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;


CREATE USER aoo_tests
  IDENTIFIED BY AOO_TESTS
  DEFAULT TABLESPACE app_data
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

-- 2 System Privileges for AOO_TESTS
GRANT CREATE SESSION TO AOO_TESTS;
GRANT UNLIMITED TABLESPACE TO AOO_TESTS;
GRANT CREATE MATERIALIZED VIEW TO AOO_TESTS;
GRANT ALTER SESSION        TO AOO_TESTS;
GRANT ANALYZE ANY          TO AOO_TESTS;
GRANT CREATE ANY SYNONYM   TO AOO_TESTS;
GRANT CREATE CREDENTIAL    TO AOO_TESTS;
GRANT CREATE JOB           TO AOO_TESTS;
GRANT CREATE PROCEDURE     TO AOO_TESTS;
GRANT CREATE SEQUENCE      TO AOO_TESTS;
GRANT CREATE SESSION       TO AOO_TESTS;
GRANT CREATE SYNONYM       TO AOO_TESTS;
GRANT CREATE TABLE         TO AOO_TESTS;
GRANT CREATE TRIGGER       TO AOO_TESTS;
GRANT CREATE TYPE          TO AOO_TESTS;
GRANT CREATE VIEW          TO AOO_TESTS;
GRANT SELECT ANY TABLE     TO AOO_TESTS;
ALTER USER AOO_TESTS QUOTA UNLIMITED ON DATEN;

exec dbms_service.create_service('XE','XE');
exec dbms_service.start_service('XE');

CREATE OR REPLACE TRIGGER SYS.ROLE_TRIGGER AFTER STARTUP ON DATABASE
begin
      dbms_service.start_service('XE');
end;
/
exit;
EOF
