#!/bin/bash

# git clone https://github.com/oracle/docker-images.git

# cd docker-images/OracleDatabase/SingleInstance/dockerfiles
# ./buildContainerImage.sh -v 18.4.0 -x

echo "oracle image build script complete."

# docker image ls

# docker tag oracle/database:18.4.0-xe diemobiliar/oraclexe-image:18.4.0-xe
# docker push diemobiliar/oraclexe-image:18.4.0-xe
